### ISSUE TITLE
Test everything with Post Man

### ISSUE THREAD

**Issue by NightingaleMedia** [2020-Spring-Cohort/artists-albums-songs-purple-haze#33]
Artists
Albums
Song (single song with data)

Album Controller can serve up album and all songs on  album (single album view)

Artist Controller can serve up single artist and all his /her albums. 

(single artist view)

**Comment by JHardeman** [comment]
Albums and a single Album can be viewed via P.M.
Songs and a single Song can be viewed
Artists and a single Artist can be viewed via P.M.
